right_gripper_stiffness_controller:
  ros__parameters:
    joints:
      - openarm_right_finger_joint1
    interface_name: stiffness

left_gripper_stiffness_controller:
  ros__parameters:
    joints:
      - openarm_left_finger_joint1
    interface_name: stiffness
